### PR TITLE
Images 

### PR DESCRIPTION
**Pull request by loiemilio**
This version of clio tool is able to download images from friendfeed-media.com server.

### CODE REVIEW

**Comment by indeyets** [comment]
@el1073 can you please:
1. squash the commits of pull-request
2. remove formatting changes from pull-request

right now it is close to unreadable, unfortunately

**Comment by loiemilio** [comment]
no problem, just need to find time for it

**Comment by zverok** [comment]
@el1073 I've almost finished new version of Clio, with images/mp3 downloading, HTML rendering and so on. I will need 3-4 days to localize it into English (currently Russian-only), so it will be usable for everyone.

**Comment by loiemilio** [comment]
@zverok good to know, I can so close this pull request

**Pull request closed without merging**
